name = "giji"
type = "javascript"
account_id = "<your-account-id>"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./.cloudflare_build_output/assets"
entry-point = "./.cloudflare_build_output/worker"