export declare const tickSecondly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickMinutely: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickHourly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickDaily: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickWeekly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickMonthly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickQuarterly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickYearly: import("svelte/store").Readable<import("./tempo").Tempo>;
export declare const tickDecadely: import("svelte/store").Readable<import("./tempo").Tempo>;
