import type { AccountID, FaceID } from '../_type/id';
import type { presentation } from '../_type/string';
import type { BOOK_STORY_IDX, BOOK_STORY_ID, BOOK_EVENT_IDX, BOOK_EVENT_ID, BOOK_FOLDER_IDX, BookEvent, BookStory, BookPotof, BOOK_POTOF_ID, CHR_SET_IDX, Face } from '../map-reduce';
export declare type BookMessage = {
    _id: BOOK_MESSAGE_ID;
    story_id: BOOK_STORY_ID;
    event_id: BOOK_EVENT_ID;
    sow_auth_id: AccountID;
    potof_id?: BOOK_POTOF_ID;
    face_id?: FaceID;
    mention_ids: BOOK_MESSAGE_ID[];
    story: BookStory;
    event: BookEvent;
    potof?: BookPotof;
    face?: Face;
    write_at: Date;
    date?: string;
    show: CHAT;
    handle: HANDLE;
    mestype?: MesType;
    group: GroupType;
    subid?: SubType;
    logid?: `${BOOK_PHASE_IDX}-${BOOK_MESSAGE_IDX}`;
    csid?: CHR_SET_IDX;
    size?: number;
    deco: '' | 'head' | 'mono' | 'logo';
    style?: StyleType;
    name?: presentation;
    to?: presentation;
    log: presentation;
};
export declare type BOOK_PHASE_IDX = `${LogType}${SubType}` | 'MM' | 'AIM';
export declare type BOOK_PHASE_ID = `${BOOK_FOLDER_IDX}-${BOOK_STORY_IDX}-${BOOK_EVENT_IDX}-${LogType}${SubType}`;
export declare type BOOK_MESSAGE_IDX = `${number | 'CAST' | 'vrule' | 'welcome' | 'title'}`;
export declare type BOOK_MESSAGE_ID = `${BOOK_FOLDER_IDX}-${BOOK_STORY_IDX}-${BOOK_EVENT_IDX}-${BOOK_PHASE_IDX}-${BOOK_MESSAGE_IDX}`;
export declare type CHAT = typeof CHAT[number];
export declare type HANDLE = typeof HANDLE[number];
export declare type StyleType = typeof StyleType[number];
export declare type MesType = typeof MesType[number];
export declare type LogType = typeof LogType[number];
export declare type SubType = typeof SubType[number];
export declare type GroupType = typeof GroupType[number];
export declare const CHAT: string[];
export declare const HANDLE: readonly ["TITLE", "MAKER", "ADMIN", "AIM", "GAIM", "TSAY", "SSAY", "VSSAY", "MSAY", "GSAY", "VGSAY", "WSAY", "PSAY", "HSAY", "LSAY", "XSAY", "FSAY", "ELSE", "hide", "private", "public"];
export declare const StyleType: readonly ["text", "head", "mono"];
export declare const MesType: readonly ["CAST", "ADMIN", "MAKER", "INFOSP", "INFONOM", "INFOWOLF", "AIM", "TSAY", "WSAY", "GSAY", "VSAY", "BSAY", "SPSAY", "SAY", "DELETED"];
export declare const LogType: readonly ["c", "a", "m", "i", "I", "T", "W", "S", "D"];
export declare const SubType: readonly ["A", "I", "M", "S", "B"];
export declare const GroupType: readonly ["A", "I", "M", "S"];
