export declare const hiraganaHead: string;
export declare const katakanaHead: string;
export declare const small: (str: string) => string;
export declare const sub: (str: string) => string;
export declare const smallcap: (str: string) => string;
export declare const sup: (str: string) => string;
export declare const rune: (str: string) => string;
export declare const bbb: (str: string) => string;
export declare const cursive: (str: string) => string;
export declare const cursiveBold: (str: string) => string;
export declare const fraktur: (str: string) => string;
export declare const region: (str: string) => string;
export declare const square: (str: string) => string;
export declare const squared: (str: string) => string;
export declare const squareBlack: (str: string) => string;
export declare const circled: (str: string) => string;
export declare const circleBlack: (str: string) => string;
export declare const ascii: (str: string) => string;
export declare function hira2kata(str: string): string;
export declare function kata2hira(str: string): string;
export declare function swapKana(str: string): string;
export declare function devoice(str: string): string;
export declare function semiVoice(str: string): string;
export declare function fullVoice(str: string): string;
